### PR TITLE
[FIX] Promises Thenable Type, Media Find Type

### PR DESCRIPTION
**Pull request by rajatkaush1k**
Also includes eslint updates & a test file with my dummy configuration.
Contains the fix for [Issues/18](https://github.com/cosmicjs/cosmic-sdk-js/issues/18)

### CODE REVIEW

**Review by tonyspiro — APPROVED** [review]
LGTM

**Comment by rajatkaush1k** [comment]
Waiting for @jazibsawar's approval.
Will remove the test file and merge once approved.

**Comment by jazibsawar** [comment]
I refactored to clean up the code. One scenario is not working though, 

```
cosmic.media.findOne({})
  .then(res => console.log(res))
  .catch(err => console.log('THIS NEVER GETS CALLED EVEN ERROR');
```

**Comment by rajatkaush1k** [comment]
> I refactored to clean up the code. One scenario is not working though,
> 
> ```
> cosmic.media.findOne({})
>   .then(res => console.log(res))
>   .catch(err => console.log('THIS NEVER GETS CALLED EVEN ERROR');
> ```

Thanks for the cleanup. I've included a new condition in findOne parameter object to not be empty. Looks like the condition never goes into the catch block because the request pulls through successfully in the try block, which it shouldn't - making me wonder if we're considering this as a valid request on our backend.

**Comment by jazibsawar** [comment]
> > I refactored to clean up the code. One scenario is not working though,
> > ```
> > cosmic.media.findOne({})
> >   .then(res => console.log(res))
> >   .catch(err => console.log('THIS NEVER GETS CALLED EVEN ERROR');
> > ```
> 
> Thanks for the cleanup. I've included a new condition in findOne method for the parameter object to not be empty. Looks like the condition never goes into the catch block because the request pulls through successfully in the try block, which it shouldn't - making me wonder if we're considering this as a valid request on our backend.

It wasn't about an error from the backend. It doesn't go to catch even if there is an error. I tested it by throwing an error

**Comment by rajatkaush1k** [comment]
> > > I refactored to clean up the code. One scenario is not working though,
> > > ```
> > > cosmic.media.findOne({})
> > >   .then(res => console.log(res))
> > >   .catch(err => console.log('THIS NEVER GETS CALLED EVEN ERROR');
> > > ```
> > 
> > 
> > Thanks for the cleanup. I've included a new condition in findOne method for the parameter object to not be empty. Looks like the condition never goes into the catch block because the request pulls through successfully in the try block, which it shouldn't - making me wonder if we're considering this as a valid request on our backend.
> 
> It wasn't about an error from the backend. It doesn't go to catch even if there is an error. I tested it by throwing an error

I tried passing in an invalid string value (for which it should throw an error) and it did the error handling correctly for me.

Can you try with .findOne({ original_name: 'bad_request' }) in the test file to confirm?

**Comment by jazibsawar** [comment]
> > > > I refactored to clean up the code. One scenario is not working though,
> > > > ```
> > > > cosmic.media.findOne({})
> > > >   .then(res => console.log(res))
> > > >   .catch(err => console.log('THIS NEVER GETS CALLED EVEN ERROR');
> > > > ```
> > > 
> > > 
> > > Thanks for the cleanup. I've included a new condition in findOne method for the parameter object to not be empty. Looks like the condition never goes into the catch block because the request pulls through successfully in the try block, which it shouldn't - making me wonder if we're considering this as a valid request on our backend.
> > 
> > 
> > It wasn't about an error from the backend. It doesn't go to catch even if there is an error. I tested it by throwing an error
> 
> I tried passing in an invalid string value (for which it should throw an error) and it did the error handling correctly for me.
> 
> Can you try with .findOne({ original_name: 'bad_request' }) in the test file to confirm?
> 
> In your specific case with the empty object ({}) it did not go into the catch statement.

Are you using `try-catch`? Try catch do work. But `then().catch()` doesn't for me. I'll try again

**Comment by rajatkaush1k** [comment]
> > > > > I refactored to clean up the code. One scenario is not working though,
> > > > > ```
> > > > > cosmic.media.findOne({})
> > > > >   .then(res => console.log(res))
> > > > >   .catch(err => console.log('THIS NEVER GETS CALLED EVEN ERROR');
> > > > > ```
> > > > 
> > > > 
> > > > Thanks for the cleanup. I've included a new condition in findOne method for the parameter object to not be empty. Looks like the condition never goes into the catch block because the request pulls through successfully in the try block, which it shouldn't - making me wonder if we're considering this as a valid request on our backend.
> > > 
> > > 
> > > It wasn't about an error from the backend. It doesn't go to catch even if there is an error. I tested it by throwing an error
> > 
> > 
> > I tried passing in an invalid string value (for which it should throw an error) and it did the error handling correctly for me.
> > Can you try with .findOne({ original_name: 'bad_request' }) in the test file to confirm?
> > In your specific case with the empty object ({}) it did not go into the catch statement.
> 
> Are you using `try-catch`? Try catch do work. But `then().catch()` doesn't for me. I'll try again

Ah, gotcha. I was using Try-catch in the function. Just tried with the chaining methods and catch isn't working.

**Pull request merged**
